### fetch quotes from zen
GET https://zenquotes.io/api/quotes

### fetch random quote from zen
GET https://zenquotes.io/api/random

### fetch random quote with GET
GET http://localhost:8180/api/v1/quote

### fetch random quote with POST and idsToExclude
POST http://localhost:8180/api/v1/quote
Content-Type: application/json

[1,2,3,4,5]

### like a quote with PATCH and id
PATCH http://localhost:8180/api/v1/quote/5/like

### fetch all liked quotes with GET
GET http://localhost:8180/api/v1/quote/liked



